name: cargo test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check rust version
        run: rustup show
      - name: Run tests
        run: |
          cargo test
          cargo test -F tracing-support --doc
